sudo: false

# services:
#   - docker

# install:
#   - docker --version

# script:
#   - docker build -t release .

# deploy:
#   provider: releases
#   api_key: "GITHUB OAUTH TOKEN"
#   file: "FILE TO UPLOAD"
#   skip_cleanup: true
#   on:
#     tags: true

language: go

go:
  - "1.10.x"

install:
  - lsb_release -a
  - node -v
  - go version

script:
  - go get github.com/gobuffalo/packr/packr
  - pwd
  - ls
  - NODE_ENV=production make web-dep frontend server agent
