sudo: required

# services:
#   - docker

# install:
#   - docker --version

# script:
#   - docker build -t release .

# deploy:
#   provider: releases
#   api_key: "GITHUB OAUTH TOKEN"
#   file: "FILE TO UPLOAD"
#   skip_cleanup: true
#   on:
#     tags: true

install:
  - lsb_release -a

script:
  - go get github.com/gobuffalo/packr/packr
  - NODE_ENV=production make web-dep frontend server agent
