sudo: false

language: go

go:
  - "1.10.x"

install:
  - lsb_release -a
  - node -v
  - go version

script:
  - go get github.com/gobuffalo/packr/packr
  - pwd
  - ls
  - NODE_ENV=production make web-dep frontend server agent
  - ls artifacts

deploy:
  provider: releases
  api_key: $GH_OAUTH
  file_glob: true
  file: artifacts/*
  skip_cleanup: true
  on:
    tags: true
