sudo: false

# services:
#   - docker

# install:
#   - docker --version

# script:
#   - docker build -t release .

# deploy:
#   provider: releases
#   api_key: "GITHUB OAUTH TOKEN"
#   file: "FILE TO UPLOAD"
#   skip_cleanup: true
#   on:
#     tags: true

install:
  - lsb_release -a
  - node -v
  - gimme force 1.11.1
  - go version

script:
  - go get github.com/gobuffalo/packr/packr
  - export WD="$GOPATH/github.com/misha-plus/power-start"
  - mkdir -p $WD
  - cp -R $PWD/* $WD
  - cd $WD
  - pwd
  - ls
  - echo $GOPATH
  - NODE_ENV=production make web-dep frontend server agent
