sudo: false

language: go

go:
  - "1.11.x"

install:
  - lsb_release -a
  - node -v
  - go version

script:
  - go get github.com/gobuffalo/packr/packr
  - pwd
  - ls
  - NODE_ENV=production make web-dep frontend
  - pushd server
  - packr
  - GOOS="linux"  GOARCH="amd64" go build -o ../artifacts/power-start-server-linux-amd64 *.go
  - GOOS="linux"  GOARCH="386"   go build -o ../artifacts/power-start-server-linux-x86 *.go
  - GOOS="linux"  GOARCH="arm" GOARM="6" go build -o ../artifacts/power-start-server-linux-arm *.go
  - GOOS="linux"  GOARCH="arm64" go build -o ../artifacts/power-start-server-linux-arm64 *.go
  - GOOS="darwin" GOARCH="amd64" go build -o ../artifacts/power-start-server-mac-amd64 *.go
  - popd
  - GOOS="linux"  GOARCH="amd64" go build -o artifacts/power-start-agent-linux-amd64 agent/agent.go
  - GOOS="linux"  GOARCH="386"   go build -o artifacts/power-start-agent-linux-x86 agent/agent.go
  - GOOS="linux"  GOARCH="arm" GOARM="6" go build -o artifacts/power-start-agent-linux-arm agent/agent.go
  - GOOS="linux"  GOARCH="arm64" go build -o artifacts/power-start-agent-linux-arm64 agent/agent.go
  - GOOS="darwin" GOARCH="amd64" go build -o artifacts/power-start-agent-mac-amd64 agent/agent.go
  - ls artifacts
  - cp *.ini artifacts/
  - rm -rf web/build
  - ./artifacts/power-start-server-linux-amd64 &
  - sleep 10
  - curl http://localhost:4000/ -f -v

deploy:
  provider: releases
  api_key: $GH_OAUTH
  file_glob: true
  file:
    - artifacts/*
  skip_cleanup: true
  on:
    tags: true
