version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
      
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout

      - run: mkdir artifacts
      - run: ls -laR
      - run: go build -o artifacts/power-start-agent agent/*.go
      - run: go build -o artifacts/power-start-server server/*.go
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: artifacts
          # Must be relative path from root
          paths:
            - power-start-agent
            - power-start-server
      
  release:
    docker:
      - image: circleci/golang:1.9
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: artifacts
      - run: ls artifacts
      - run: go get github.com/tcnksm/ghr
      - run: ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME -prerelease $CIRCLE_TAG artifacts
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
      - release:
          requires:
            - build
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
  # untagged:
  #   jobs:
  #     - build:
  #         filters:
  #           tags:
  #             ignore: /^v.*/
  # tagged:
  #   jobs:
  #     - build
  #     - release:
  #         requires:
  #           - build
  #     tags:
  #       only: /^v.*/
          
